groups:
  search:
    count: 5
    container: base
  clustermanager:
    count: 3
    container: base
  indexer:
    count: 5
    container: base
  deployer:
    count: 1
    container: base
  licensemanager:
    count: 1
    container: base


containers:
  base:
    image: valshatravenko/debian-sshd
    ports:
      - 8089
    volumes:
      - $PWD/output/id_test.pub:/home/ansible/.ssh/authorized_keys
      - $dynamic:/opt/splunk
