connection_type: ssh
filters:
- include: inventory_hostname.startswith('ap')
- exclude: true
groups:
  deployer: '"deployer" in docker_name'
  licensemanager: '"licensemanager" in docker_name'
plugin: community.docker.docker_containers
strict: true
